export enum Role {
  JSB_GS = 1,
  JSB_FBZ = 2,
  JSB_BZ = 3,
  XMB_BZ = 4,
  XMB_FBZ = 5,
  XMB_GS = 6,
  SFB_GS = 7,
  SFB_FBZ = 8,
  SFB_BZ = 9,
  ZXB_BZ = 10,
  ZXB_FBZ = 11,
  ZXB_GS = 12,
  MSC_GS = 13,
  MSC_FMS = 14,
  MSC_MSZ = 15,
  LSH_HZ = 16,
  LSH_JSFHZ = 17,
  LSH_CWFHZ = 18,
  LSH_ZGFZR = 19,
  member = 20,
}
export const AdminRole = [
  Role.JSB_BZ,
  Role.JSB_FBZ,
  Role.LSH_CWFHZ,
  Role.LSH_HZ,
  Role.LSH_JSFHZ,
  Role.LSH_ZGFZR,
  Role.MSC_FMS,
  Role.MSC_MSZ,
  Role.SFB_BZ,
  Role.SFB_FBZ,
  Role.XMB_BZ,
  Role.XMB_FBZ,
  Role.ZXB_BZ,
  Role.ZXB_FBZ
]